# Generated by Django 3.2.5 on 2021-08-25 21:43

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('birthday', models.DateField(default=datetime.date(2000, 1, 1), validators=[users.utils.age_validator])),
                ('avatar', models.ImageField(default='users/sellers/NO_AVATAR.png', upload_to='users/sellers')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+79991112233', max_length=128, region=None)),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'sellers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
