# Generated by Django 3.2.5 on 2021-08-23 15:29

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79991112233', max_length=128, region=None),
        ),
    ]
