# Generated by Django 3.2.5 on 2021-08-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autolisting_set', to='main.category'),
        ),
        migrations.AlterField(
            model_name='autolisting',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autolisting',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autolisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autolisting_set', to='main.seller'),
        ),
        migrations.AlterField(
            model_name='autolisting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='autolisting_set', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemlisting_set', to='main.category'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemlisting_set', to='main.seller'),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='itemlisting_set', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicelisting_set', to='main.category'),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicelisting_set', to='main.seller'),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='servicelisting_set', to='main.Tag'),
        ),
    ]
