# Generated by Django 3.2.5 on 2021-08-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_price_defaults(apps, schema_editor):
        Listing = apps.get_model('main', 'Listing')
        Listing.objects.all().update(price=0)
    
    dependencies = [
        ('main', '0003_auto_20210728_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunPython(set_price_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
