# Generated by Django 3.2.5 on 2021-08-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('main', '0004_seller_birthday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
