# Generated by Django 3.2.5 on 2021-08-05 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
