# Generated by Django 3.2.5 on 2021-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_seller_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(default='sellers/NO_AVATAR.png', upload_to='sellers'),
        ),
    ]
