# Generated by Django 3.2.5 on 2021-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_seller_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(default='%(app_label)s/%(class)s/NO_AVATAR.png', upload_to='%(app_label)s/%(class)s'),
        ),
    ]
