# Generated by Django 3.2.5 on 2021-08-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_seller_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='avatar',
            field=models.ImageField(default='main/sellers/NO_AVATAR.png', upload_to='main/sellers'),
        ),
    ]
