# Generated by Django 3.2.5 on 2021-08-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='main/cars/NO_IMAGE.jpg', upload_to='main/cars'),
        ),
    ]
