# Generated by Django 3.2.5 on 2021-08-09 13:52

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='birthday',
            field=models.DateField(validators=[main.validators.age_validator]),
        ),
    ]
