# Generated by Django 3.2.5 on 2021-08-10 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_seller_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolisting',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Minimal weight is 0.01 kg'), django.core.validators.DecimalValidator(decimal_places=2, max_digits=4)]),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='weight',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0.01, message='Minimal weight is 0.01 kg'), django.core.validators.DecimalValidator(decimal_places=2, max_digits=4)]),
        ),
    ]
