# Generated by Django 3.2.5 on 2021-08-10 14:04

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_seller_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolisting',
            name='weight',
            field=models.FloatField(validators=[main.validators.weight_validator]),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='weight',
            field=models.FloatField(validators=[main.validators.weight_validator]),
        ),
    ]
