# Generated by Django 3.2.5 on 2021-08-13 11:08

import datetime
from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210810_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='birthday',
            field=models.DateField(default=datetime.date(2000, 1, 1), validators=[main.validators.age_validator]),
        ),
    ]
