# Generated by Django 3.2.5 on 2021-08-10 13:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210810_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autolisting',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='itemlisting',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.01'))]),
        ),
    ]
